wandb_version: 1

architecture:
  desc: null
  value: AutoEncoderTrainer
name:
  desc: null
  value: 20240131-181126_autoencoderAutoEncoder_AdamWoptim_1epochs_0001lr_CrossEntropyLossloss_ReLUact_00dropout_4accsteps_10evalsteps_3encconvs_3decconvs_nopool
dataset:
  desc: null
  value: Minecraft Generated Worlds
epochs:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.001
_wandb:
  desc: null
  value:
    python_version: 3.12.1
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706721087.679319
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 1
      - 16
      - 23
      4: 3.12.1
      5: 0.16.2
      8:
      - 3
      - 5
      13: windows-amd64
