encoder_conv_channels: [512, 128, 32]
decoder_conv_channels: [32, 128, 512]
dropout_rate: 0.0
criterion_name: ce
learning_rate: 1e-3
weight_decay: 0.0
accumulation_steps: 1
evaluation_steps: 10
use_scaler: True
num_epochs: 1
with_pooling: False