method: random
metric:
  goal: minimize
  name: val_loss

run_cap: 250

parameters:
  num_negative_samples:
    values: 
      - 2
      - 5
      - 10
      - 20

  batch_size:
    distribution: constant
    value: 256

  embedding_dimension:
    values: 
      - 8
      - 16
      - 32

  learning_rate:
    distribution: log_uniform_values
    max: 1e-2
    min: 1e-5

  weight_decay:
    distribution: log_uniform_values
    max: 1e-1
    min: 1e-5

  accumulation_steps:
    distribution: constant
    value: 1

  use_scaler:
    distribution: constant
    value: True

  num_epochs:
    distribution: constant
    value: 1

  noise_power:
    values:
      - 0.75
      - 0.5
      - 0.25

  minimum_noise_distribution:
    distribution: log_uniform_values
    max: 1e-3
    min: 1e-6

  subsampling_threshold:
    distribution: log_uniform_values
    max: 1e-3
    min: 1e-6

  minimum_subsampling_distribution:
    distribution: log_uniform_values
    max: 1e-3
    min: 1e-6
