method: random
metric:
  goal: minimize
  name: val_loss

run_cap: 100

parameters:
  num_negative_samples:
    values: 
      - 2
      - 5
      - 10
      - 15
      - 20

  batch_size:
    values: 
      - 32
      - 64
      - 128
      - 256

  embedding_dimension:
    values: 
      - 8
      - 16
      - 32
      - 64
      - 128

  learning_rate:
    distribution: log_uniform_values
    max: 1e-2
    min: 1e-5

  weight_decay:
    distribution: log_uniform_values
    max: 1e-1
    min: 1e-5

  accumulation_steps:
    distribution: constant
    value: 1

  use_scaler:
    distribution: constant
    value: True

  num_epochs:
    distribution: constant
    value: 1