batch_size: 256
num_negative_samples: 20
embedding_dimension: 16
accumulation_steps: 1
evaluation_steps: 100
use_scaler: True
learning_rate: 1e-3
weight_decay: 1e-4
num_epochs: 10
noise_power: 0.75
minimum_noise_distribution: 1e-5
subsampling_threshold: 1e-5
minimum_subsampling_distribution: 1e-4