PRINT_LOGS = True

N_CHUNKS_PER_REGION_PER_DIM = 32
MIN_Y = -64
MAX_Y = 320
CHUNK_Y_SIZE = MAX_Y - MIN_Y
CHUNK_XZ_SIZE = 16
SECTION_SIZE = 16
DEFAULT_N_SECTIONS_PER_CLUSTER_PER_DIM = 3
MAX_N_SECTIONS_PER_CLUSTER_PER_DIM = 32
